#!/usr/bin/env python3
"""
Helix Dependency Sentinel - Zapier Zap Creator
Creates automated dependency management Zaps via MCP

Usage:
    python create_dependency_sentinel_zaps.py
"""

import asyncio
import json
from fastmcp import Client
from fastmcp.client.transports import StreamableHttpTransport

# Your Zapier MCP server URL (replace with actual URL)
MCP_SERVER_URL = "https://mcp.zapier.com/api/mcp/s/YOUR_SERVER_ID/mcp"

async def create_dependency_scanner_zap(client):
    """
    Zap 1: Daily Dependency Scanner

    Trigger: Schedule (daily at 2am)
    Actions:
      1. Get requirements.txt from GitHub
      2. Parse dependencies
      3. Check PyPI for updates
      4. Send to Claude for security analysis
      5. Create GitHub issue if updates found
    """

    zap_config = {
        "name": "Helix Dependency Scanner",
        "description": "Daily scan of Python dependencies for updates and security issues",
        "steps": [
            {
                "type": "trigger",
                "app": "Schedule by Zapier",
                "event": "Every Day",
                "config": {
                    "time": "02:00",
                    "timezone": "America/New_York"
                }
            },
            {
                "type": "action",
                "app": "GitHub",
                "event": "Get File",
                "config": {
                    "owner": "Deathcharge",
                    "repo": "helix-unified",
                    "path": "requirements.txt",
                    "ref": "main"
                }
            },
            {
                "type": "action",
                "app": "Code by Zapier",
                "event": "Run Python",
                "config": {
                    "code": """
import re

# Parse requirements.txt
requirements = input_data.get('file_content', '')
packages = []

for line in requirements.split('\\n'):
    line = line.strip()
    if line and not line.startswith('#'):
        match = re.match(r'^([a-zA-Z0-9_-]+)([>=<]+)?([0-9.]+)?', line)
        if match:
            packages.append({
                'name': match.group(1),
                'current_version': match.group(3) or 'latest'
            })

return {'packages': packages}
"""
                }
            },
            {
                "type": "action",
                "app": "HTTP by Zapier",
                "event": "GET Request",
                "config": {
                    "url": "https://pypi.org/pypi/{{package_name}}/json",
                    "description": "Get latest version from PyPI"
                },
                "loop": "packages"
            },
            {
                "type": "action",
                "app": "Claude (Anthropic)",
                "event": "Conversation",
                "config": {
                    "model": "claude-sonnet-4",
                    "prompt": """Analyze these Python package updates for the helix-unified repository:

Current packages: {{packages}}
Latest versions from PyPI: {{pypi_data}}

For each package that has an update:
1. Check for security vulnerabilities (CVEs)
2. Review breaking changes in changelog
3. Assess compatibility with Python 3.11+
4. Recommend: SAFE_PATCH, NEEDS_REVIEW, or BREAKING_CHANGE

Return JSON:
{
  "updates": [
    {"package": "name", "current": "1.0", "latest": "1.1", "recommendation": "SAFE_PATCH", "reasoning": "..."}
  ],
  "action": "create_pr" | "create_issue" | "none"
}"""
                }
            },
            {
                "type": "action",
                "app": "Filter by Zapier",
                "event": "Only continue if...",
                "config": {
                    "field": "claude_response.action",
                    "condition": "is not",
                    "value": "none"
                }
            },
            {
                "type": "action",
                "app": "GitHub",
                "event": "Create Issue",
                "config": {
                    "owner": "Deathcharge",
                    "repo": "helix-unified",
                    "title": "🤖 Dependency Updates Available",
                    "body": """## Helix Dependency Sentinel Report

{{claude_response.summary}}

### Recommended Updates
{{claude_response.updates}}

### Next Steps
- Review the analysis above
- Merge safe patches automatically
- Test breaking changes in dev environment

*Generated by Helix Dependency Sentinel*
""",
                    "labels": ["dependencies", "automation"]
                }
            },
            {
                "type": "action",
                "app": "Discord",
                "event": "Send Channel Message",
                "config": {
                    "channel_id": "YOUR_DISCORD_CHANNEL",
                    "content": "🔍 **Dependency Scan Complete**\n\n{{claude_response.summary}}\n\nCheck GitHub for details."
                }
            }
        ]
    }

    print("Creating Zap 1: Dependency Scanner...")
    result = await client.callTool({
        "name": "create_zap",
        "arguments": {
            "zap_config": json.dumps(zap_config)
        }
    })
    print(f"✅ Created: {result}")
    return result


async def create_smart_pr_merger_zap(client):
    """
    Zap 2: Smart PR Auto-Merger

    Trigger: GitHub PR opened (by Helix bot)
    Actions:
      1. Get PR diff
      2. Send to Claude for analysis
      3. If safe → merge PR
      4. If risky → request human review
    """

    zap_config = {
        "name": "Helix Smart PR Merger",
        "description": "Auto-merge safe dependency PRs after Claude analysis",
        "steps": [
            {
                "type": "trigger",
                "app": "GitHub",
                "event": "New Pull Request",
                "config": {
                    "owner": "Deathcharge",
                    "repo": "helix-unified",
                    "filter": {
                        "user": "helix-bot",
                        "labels": ["dependencies", "automation"]
                    }
                }
            },
            {
                "type": "action",
                "app": "GitHub",
                "event": "Get PR Diff",
                "config": {
                    "pr_number": "{{trigger.number}}"
                }
            },
            {
                "type": "action",
                "app": "Claude (Anthropic)",
                "event": "Conversation",
                "config": {
                    "model": "claude-sonnet-4",
                    "prompt": """You are a senior DevOps engineer reviewing this dependency update PR.

PR Title: {{trigger.title}}
PR Description: {{trigger.body}}
Diff: {{pr_diff}}

Analyze:
1. What packages are being updated?
2. Are there breaking changes in the diff?
3. Will this affect existing functionality?
4. Are tests included/passing?
5. Is this a security patch?

Return JSON:
{
  "safe_to_merge": true/false,
  "confidence": "high" | "medium" | "low",
  "reasoning": "Detailed explanation",
  "action": "merge" | "request_review" | "reject"
}"""
                }
            },
            {
                "type": "action",
                "app": "Filter by Zapier",
                "event": "Only continue if...",
                "config": {
                    "field": "claude_analysis.action",
                    "condition": "is",
                    "value": "merge"
                }
            },
            {
                "type": "action",
                "app": "GitHub",
                "event": "Merge Pull Request",
                "config": {
                    "pr_number": "{{trigger.number}}",
                    "merge_method": "squash",
                    "commit_message": "🤖 Auto-merged by Helix Sentinel: {{claude_analysis.reasoning}}"
                }
            },
            {
                "type": "action",
                "app": "Discord",
                "event": "Send Channel Message",
                "config": {
                    "channel_id": "YOUR_DISCORD_CHANNEL",
                    "content": "✅ **Auto-merged PR**\n\nPR #{{trigger.number}}: {{trigger.title}}\n\nClaude's analysis: {{claude_analysis.reasoning}}"
                }
            }
        ],
        "paths": [
            {
                "condition": "claude_analysis.action == 'request_review'",
                "steps": [
                    {
                        "type": "action",
                        "app": "GitHub",
                        "event": "Add PR Comment",
                        "config": {
                            "pr_number": "{{trigger.number}}",
                            "body": """🤖 **Helix Sentinel Analysis**

{{claude_analysis.reasoning}}

⚠️ **Action Required:** This PR needs human review before merging.

Confidence: {{claude_analysis.confidence}}
"""
                        }
                    },
                    {
                        "type": "action",
                        "app": "Discord",
                        "event": "Send Channel Message",
                        "config": {
                            "channel_id": "YOUR_DISCORD_CHANNEL",
                            "content": "@Andrew ⚠️ **PR needs review**\n\nPR #{{trigger.number}}: {{trigger.title}}\n\n{{claude_analysis.reasoning}}"
                        }
                    }
                ]
            }
        ]
    }

    print("Creating Zap 2: Smart PR Merger...")
    result = await client.callTool({
        "name": "create_zap",
        "arguments": {
            "zap_config": json.dumps(zap_config)
        }
    })
    print(f"✅ Created: {result}")
    return result


async def create_security_alert_handler_zap(client):
    """
    Zap 3: Security Alert Handler

    Trigger: GitHub Security Advisory (or manual webhook)
    Actions:
      1. Parse security advisory
      2. Send to Claude for impact analysis
      3. Create urgent PR if critical
      4. Alert Discord immediately
    """

    zap_config = {
        "name": "Helix Security Alert Handler",
        "description": "Immediate response to critical security vulnerabilities",
        "steps": [
            {
                "type": "trigger",
                "app": "Webhooks by Zapier",
                "event": "Catch Hook",
                "config": {
                    "description": "Receives security alerts from GitHub or manual triggers"
                }
            },
            {
                "type": "action",
                "app": "Claude (Anthropic)",
                "event": "Conversation",
                "config": {
                    "model": "claude-sonnet-4",
                    "prompt": """You are a security engineer analyzing this vulnerability:

Package: {{trigger.package}}
Current Version: {{trigger.current_version}}
Vulnerable Versions: {{trigger.vulnerable_versions}}
CVE: {{trigger.cve}}
Severity: {{trigger.severity}}
Description: {{trigger.description}}

Repository: helix-unified (Python 3.11, FastAPI, Discord bot)

Analyze:
1. Does this affect our current version?
2. What is the attack vector?
3. Can this be exploited in our environment?
4. What's the urgency? (critical/high/medium/low)
5. Recommended fix version

Return JSON:
{
  "affects_us": true/false,
  "urgency": "critical" | "high" | "medium" | "low",
  "impact": "Description of potential impact",
  "fix_version": "1.2.3",
  "immediate_action": "Update immediately" | "Schedule update" | "Monitor"
}"""
                }
            },
            {
                "type": "action",
                "app": "Filter by Zapier",
                "event": "Only continue if...",
                "config": {
                    "field": "claude_analysis.affects_us",
                    "condition": "is",
                    "value": "true"
                }
            },
            {
                "type": "action",
                "app": "Code by Zapier",
                "event": "Run Python",
                "config": {
                    "code": """
# Generate updated requirements.txt with security fix
import re

package = input_data['package']
fix_version = input_data['fix_version']
requirements = input_data['current_requirements']

updated = []
for line in requirements.split('\\n'):
    if line.strip().startswith(package):
        # Update version
        updated.append(f"{package}=={fix_version}")
    else:
        updated.append(line)

return {
    'updated_requirements': '\\n'.join(updated),
    'pr_title': f'🚨 Security Fix: Update {package} to {fix_version}',
    'pr_body': f'''## Security Update

**Package:** {package}
**CVE:** {input_data.get("cve", "N/A")}
**Severity:** {input_data.get("severity", "Unknown")}

### Impact Analysis (by Claude)
{input_data.get("impact", "")}

### Changes
- Updated {package} from {input_data.get("current_version")} to {fix_version}

**Urgency:** {input_data.get("urgency", "high")}
**Action:** {input_data.get("immediate_action", "Review and merge ASAP")}

*Auto-generated by Helix Security Sentinel*
'''
}
"""
                }
            },
            {
                "type": "action",
                "app": "GitHub",
                "event": "Create Pull Request",
                "config": {
                    "owner": "Deathcharge",
                    "repo": "helix-unified",
                    "title": "{{pr_title}}",
                    "body": "{{pr_body}}",
                    "head": "security/{{trigger.cve}}",
                    "base": "main",
                    "files": [
                        {
                            "path": "requirements.txt",
                            "content": "{{updated_requirements}}"
                        }
                    ],
                    "labels": ["security", "critical", "automation"]
                }
            },
            {
                "type": "action",
                "app": "Discord",
                "event": "Send Channel Message",
                "config": {
                    "channel_id": "YOUR_DISCORD_CHANNEL",
                    "content": """@Andrew 🚨 **CRITICAL SECURITY ALERT**

**Package:** {{trigger.package}}
**CVE:** {{trigger.cve}}
**Severity:** {{trigger.severity}}

**Claude's Impact Analysis:**
{{claude_analysis.impact}}

**Action Taken:**
Created PR with security fix: {{pr_url}}

**Urgency:** {{claude_analysis.urgency}}
**Recommendation:** {{claude_analysis.immediate_action}}
"""
                }
            }
        ]
    }

    print("Creating Zap 3: Security Alert Handler...")
    result = await client.callTool({
        "name": "create_zap",
        "arguments": {
            "zap_config": json.dumps(zap_config)
        }
    })
    print(f"✅ Created: {result}")
    return result


async def main():
    """Create all Helix Dependency Sentinel Zaps"""

    print("🤖 Helix Dependency Sentinel - Zap Creator")
    print("=" * 60)

    # Initialize MCP client
    transport = StreamableHttpTransport(MCP_SERVER_URL)
    client = Client(transport=transport)

    async with client:
        print(f"✅ Connected to Zapier MCP: {client.is_connected()}\n")

        # Create all 3 Zaps
        try:
            zap1 = await create_dependency_scanner_zap(client)
            zap2 = await create_smart_pr_merger_zap(client)
            zap3 = await create_security_alert_handler_zap(client)

            print("\n" + "=" * 60)
            print("✅ ALL ZAPS CREATED SUCCESSFULLY!")
            print("=" * 60)
            print("\nYour Helix Dependency Sentinel is now active with:")
            print("  1. Daily dependency scanner")
            print("  2. Smart PR auto-merger")
            print("  3. Security alert handler")
            print("\nNext steps:")
            print("  - Test each Zap manually in Zapier UI")
            print("  - Update Discord channel IDs")
            print("  - Enable all Zaps")

        except Exception as e:
            print(f"❌ Error creating Zaps: {e}")
            raise

    print("\n🎉 Helix Dependency Sentinel is ready!")


if __name__ == "__main__":
    # Make sure to install dependencies first:
    # pip install fastmcp
    asyncio.run(main())
